### ISSUE TITLE
Can we unify ca_Path and truststore_path?

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-mixin-http_client#1]
Would be nice if users could just specify the path to the trusted CA and we just 'do the right thing' if it's PEM, PKCS12, or JKS format. Thoughts?

**Comment by andrewvc** [comment]
Well, I think it's tricky because these files frequently don't have extensions. Trust store files often times don't end in JKS (cacert is a popular name in examples), and I've seen PEM files with all manner of names as well. 

Additionally, these two things are actually two separate properties in Apache's [SSLContextBuilder](https://hc.apache.org/httpcomponents-core-dev/httpcore/apidocs/org/apache/http/ssl/SSLContextBuilder.html). I'm not sure what happens if you set both, but if they allow you to use both I think we should.

My vote is to keep it explicit here.

I do see an issue here where I need to let users configure the truststore type explicitly. Manticore will try to figure it out from filename (and default to JKS), but this should be exposed.

**Comment by andrewvc** [comment]
@jordansissel any thoughts here? @suyograo any thoughts here?

**Comment by suyograo** [comment]
My vote is to leave it explicit. I like to specifically know I am using `.pem` vs `.jks`. Also consistent with https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L283.

@andrewvc suggest we make the config names consistent. I like the explicit use of `_path` but unfortunately ES output is released and changing it there would mean being backward compatible and such. What do you think of using `cacert` and `truststore` here?

**Comment by andrewvc** [comment]
@suyograo I'm fine with just chopping off `_path`. @jordansissel I think given @suyograo 's comments we should just not merge these two options. However, I already released the 1.0.0 version of this gem, but since no one is likely using it (yet) I'm ok with changing the API for 1.0.1

**Comment by jordansissel** [comment]
My preference would be to move towards one setting that did-the-right-thing. File extensions are  possible, but another alternative would be to try loading a given file as PKCS12, if that fails, try PEM, if that fails, try JKS, etc, and notify the user of the failure.

However, I am OK if we have some interim solution where folks are required to be specific about the type of file to load.

**Comment by andrewvc** [comment]
@jordansissel I think that short of writing our own JKS/PEM parser we just won't be able to automatically pick the right thing. I think the benefit there for the added complexity and effort (incl. maintenance) doesn't make sense.

I think that most people will either use one type of store or the other and as long as the documentation is explicit it won't be an issue.
