### ISSUE TITLE
Add support for using forwarding proxy

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-mixin-http_client#8]
We should be able to use http proxy to pull data. With manticore client, it should be straightforward to pass proxy URL configs. See: https://github.com/cheald/manticore/blob/master/lib/manticore/client.rb#L11

We should also investigate if we can populate these settings using the `HTTP_PROXY` environment variable or through `JAVA_OPTS`

**Comment by andrewvc** [comment]
@suyograo makes sense. I'll target this for the next release.

**Comment by andrewvc** [comment]
@suyograo forgot I already implemented this. As far as env vars go, I think it's tricky because different plugins could use different proxies. Thoughts? IMHO setting a global proxy in java makes sense for an app that needs internet access through one, but for the logstash use case it seems like a bad idea. I think making users be explicit here actually is less confusing.

**Comment by andrewvc** [comment]
I think we decided in another ticket (maybe for the ES output) that we didn't want to make this an env var for the reasons I stated. Will close this ticket.
